### ISSUE TITLE
Can't batch edit Image works

### ISSUE THREAD

**Issue by jcoyne** [samvera-labs/hyrax#1023]
It appears that `GenericWork` is hardcoded in the batch edit functionality (https://github.com/projecthydra-labs/hyrax/blob/master/app/forms/hyrax/forms/batch_edit_form.rb#L10).  This causes an error when attempting to batch edit an Image (or anything not `GenericWork`) See projecthydra-labs/hyku#1142 and projecthydra-labs/hyku#1131

**Comment by darrenleeweber** [comment]
See also related work on batch uploads to get a class name - https://github.com/projecthydra-labs/hyrax/commit/1dcc81898ce051cc831e7ddf31b1168755ea886b

**Comment by jcoyne** [comment]
@darrenleeweber This is not similar to 1dcc818 because in batch upload all rows have the same type, even though that type may be changed.  In Batch update each row should be assumed to be of a different type.

**Comment by darrenleeweber** [comment]
@jcoyne - I think @mjgiarlo was just pointing to the upload code because it has some access patterns to get the class type (or class name), in response to my slack questions about what to expect in the batch edit; i.e. does batch edit apply to various types in a batch or only one type?  So your saying that batch edit does have use cases where multiple types need to be updated (assuming they all share a common subset of attributes/fields that can be updated in batch).

**Comment by mjgiarlo** [comment]
@darrenleeweber :speech_balloon: 
> I think @mjgiarlo was just pointing to the upload code because it has some access patterns to get the class type (or class name), in response to my slack questions about what to expect in the batch edit

Yup, that's right.
