### ISSUE TITLE
make the Terms of Use configurable

### ISSUE THREAD

**Issue by hannahfrost** [samvera-labs/hyrax#406]
As the Repository Admin, I need to easily configure the text of the Terms of Use that is displayed to viewers from the repository home page, to include terms that are customized to the requirements of my local institution. 

I need to apply basic formatting to the text and to be able to include active links.

I would expect to be able configure the text in the Admin Dashboard, in the Content Blocks section under Settings.

**Comment by jcoyne** [comment]
This page is getting a little full already.  Design needed?
<img width="717" alt="screen shot 2017-02-23 at 11 16 00 pm" src="https://cloud.githubusercontent.com/assets/92044/23291439/22ced9de-fa1e-11e6-8373-87c1aedb3662.png">

**Comment by ggeisler** [comment]
It might only be a short- or medium-term solution, but we could move About Page and Help Page into a similar but new section called "Pages," leaving the others in "Content Blocks." So the Settings menu choices would become:

- Labels
- Appearance
- Pages
- Content Blocks
- Technical

That would allow for a bit more future expansion in both the Pages and Content Blocks sections before we'd face this issue again (at which point I think might consider doing something more flexible with content blocks rather than just adding more static, named ones).

**Comment by hannahfrost** [comment]
@ggeisler I really like the idea of splitting these out into two separate views: Pages and Content Blocks

**Comment by mjgiarlo** [comment]
Blocked by #538.

**Comment by mjgiarlo** [comment]
No longer blocked.

**Comment by mjgiarlo** [comment]
Done
