### ISSUE TITLE
Index visibility as a facet field

### ISSUE THREAD

**Issue by jcoyne** [samvera-labs/hyrax#485]
This will allow us to filter on different visibility levels as well as simplify SolrDocumentBehavior.

This will be used for https://github.com/projecthydra-labs/hyku/issues/447

**Comment by atz** [comment]
From previous standup, we discussed that the feature for 447 expects a single value, whereas the same visibility components might be indexed as an overlapping set of multiple values, or as distinct values in multiple fields.  (E.g., an object can have both "open access" and "embargoed" characteristics.)  If the design proceeds with a single-valued constraint, please be sure to use a single-valued solr field, so as not to conflate it with the broader case.

Relying on the index for such values will require whatever job automatically detects expiring embargoes to automatically reindex such objects.  I believe such a requirement already exists, but the timeliness of that job will affect the accuracy of that field.

**Comment by atz** [comment]
The mockup has a facet like `Visibility > Open Access`, so that is doable.  While it isn't as problematic at object-deposit time, imho, the label "Visibility" seems less apt for index/facet use.  Other things like sharing and links can affect whether-a-thing-is-visible.  I think of this more as "Audience".  I would suggest we consider changing the label across the UI.

Restating some concessions *a priori*:
- as I said, index will not automatically update to roll over Embargo/Lease state, that must happen separately
- where this field/facet power the UI, index currency and the speed of async updates may prompt user concern ("I changed my object, but it is still visible!")

**Comment by atz** [comment]
Made an empty but well-described collection via UI.  Comparison of fedora and solr views:
![screen shot 2017-05-24 at 5 09 10 pm](https://cloud.githubusercontent.com/assets/109954/26430676/f2334900-40a3-11e7-8b92-e0914061f4b1.png)
![screen shot 2017-05-24 at 5 09 30 pm](https://cloud.githubusercontent.com/assets/109954/26430675/f232a75c-40a3-11e7-9de5-eabb6f290da3.png)


Is it me, or is the visibility of the collection (in this case, "Institution") not even part of the Fedora object?

**Comment by jcoyne** [comment]
@atz it is `"read_access_group":["registered"]`

that's the same as saying authenticated visibility.

**Comment by jcoyne** [comment]
@atz but it's "the presence of 'registered' in read_groups" that determines this.  In fact all the logic is here: https://github.com/projecthydra/hydra-head/blob/master/hydra-access-controls/app/models/concerns/hydra/access_controls/visibility.rb#L20 we just need to index the result of that call.

**Comment by atz** [comment]
Yep, already looking at that, thx.
